name: CICD Cork-Up
on:
  push:
    branches:
      - main
jobs:
  kick-cicd-react:
    uses: ./.github/workflows/sub_react.yaml
    secrets: inherit

  kick-cicd-chalice:
    uses: ./.github/workflows/sub_chalice.yaml
    secrets: inherit
